# config/skills_db.py

EXTENDED_SKILL_DB = {
    # ======= プログラミング言語 =======
    'Python': {'type': 'language', 'aliases': ['py', 'python3', 'python2'], 'categories': ['backend', 'data-science', 'automation', 'scripting'], 'related': ['Django', 'Flask', 'FastAPI', 'pandas', 'numpy', 'scikit-learn']},
    'JavaScript': {'type': 'language', 'aliases': ['js', 'es6', 'es2015', 'vanillajs'], 'categories': ['frontend', 'backend']},
    'TypeScript': {'type': 'language', 'aliases': ['ts'], 'categories': ['frontend', 'backend']},
    'Java': {'type': 'language', 'aliases': ['java8', 'java11', 'java17'], 'categories': ['backend', 'enterprise']},
    'C#': {'type': 'language', 'aliases': ['csharp', '.net', 'dotnet'], 'categories': ['backend', 'windows', 'game']},
    'C++': {'type': 'language', 'aliases': ['cpp', 'c++11', 'c++14', 'c++17'], 'categories': ['system', 'game']},
    'C': {'type': 'language', 'aliases': ['c language'], 'categories': ['system', 'embedded']},
    'Go': {'type': 'language', 'aliases': ['golang'], 'categories': ['backend', 'infrastructure']},
    'Ruby': {'type': 'language', 'categories': ['backend']},
    'PHP': {'type': 'language', 'aliases': ['php7', 'php8'], 'categories': ['backend', 'web']},
    'Swift': {'type': 'language', 'categories': ['mobile', 'ios']},
    'Kotlin': {'type': 'language', 'categories': ['mobile', 'android', 'backend']},
    'Rust': {'type': 'language', 'categories': ['system', 'backend', 'webassembly']},
    'Scala': {'type': 'language', 'categories': ['backend', 'data-engineering']},
    'Dart': {'type': 'language', 'categories': ['mobile', 'frontend']},
    'R': {'type': 'language', 'categories': ['data-science', 'statistics']},
    'Perl': {'type': 'language', 'categories': ['scripting']},
    'Objective-C': {'type': 'language', 'aliases': ['obj-c', 'objc'], 'categories': ['mobile', 'ios']},
    'Shell Script': {'type': 'language', 'aliases': ['bash', 'sh', 'shell', 'zsh'], 'categories': ['scripting', 'infrastructure']},
    'SQL': {'type': 'language', 'aliases': ['pl/sql', 't-sql'], 'categories': ['database']},
    'HTML': {'type': 'language', 'aliases': ['html5', 'markup'], 'categories': ['frontend']},
    'CSS': {'type': 'language', 'aliases': ['css3', 'scss', 'sass', 'less'], 'categories': ['frontend']},
    'GraphQL': {'type': 'language', 'categories': ['api', 'backend', 'frontend']},
    'VBA': {'type': 'language', 'aliases': ['excel vba', 'macro'], 'categories': ['automation']},

    # ======= フロントエンドフレームワーク・ライブラリ =======
    'React': {'type': 'framework', 'category': 'frontend', 'aliases': ['react.js', 'reactjs']},
    'Vue.js': {'type': 'framework', 'category': 'frontend', 'aliases': ['vue', 'vuejs', 'vue3', 'vue2']},
    'Angular': {'type': 'framework', 'category': 'frontend', 'aliases': ['angular.js', 'angularjs', 'angular2+']},
    'Next.js': {'type': 'framework', 'category': 'frontend', 'aliases': ['next', 'nextjs']},
    'Nuxt.js': {'type': 'framework', 'category': 'frontend', 'aliases': ['nuxt', 'nuxtjs', 'nuxt3']},
    'Svelte': {'type': 'framework', 'category': 'frontend', 'aliases': ['sveltekit']},
    'jQuery': {'type': 'framework', 'category': 'frontend', 'aliases': ['j-query']},
    'Tailwind CSS': {'type': 'framework', 'category': 'frontend', 'aliases': ['tailwind', 'tailwindcss']},
    'Bootstrap': {'type': 'framework', 'category': 'frontend'},
    'Material-UI': {'type': 'framework', 'category': 'frontend', 'aliases': ['mui', 'material ui']},
    'Redux': {'type': 'library', 'category': 'frontend'},
    'Webpack': {'type': 'tool', 'category': 'frontend', 'aliases': ['bundler']},
    'Vite': {'type': 'tool', 'category': 'frontend'},

    # ======= バックエンドフレームワーク =======
    'Node.js': {'type': 'framework', 'category': 'backend', 'aliases': ['node', 'nodejs']},
    'Express': {'type': 'framework', 'category': 'backend', 'aliases': ['express.js']},
    'NestJS': {'type': 'framework', 'category': 'backend', 'aliases': ['nest', 'nest.js']},
    'Django': {'type': 'framework', 'category': 'backend'},
    'Flask': {'type': 'framework', 'category': 'backend'},
    'FastAPI': {'type': 'framework', 'category': 'backend'},
    'Spring Boot': {'type': 'framework', 'category': 'backend', 'aliases': ['spring', 'springboot']},
    'Laravel': {'type': 'framework', 'category': 'backend', 'aliases': ['laravel8', 'laravel9']},
    'CakePHP': {'type': 'framework', 'category': 'backend'},
    'Symfony': {'type': 'framework', 'category': 'backend'},
    'Ruby on Rails': {'type': 'framework', 'category': 'backend', 'aliases': ['rails', 'ror']},
    'Gin': {'type': 'framework', 'category': 'backend', 'aliases': ['gin-gonic']},
    'Echo': {'type': 'framework', 'category': 'backend'},
    'ASP.NET Core': {'type': 'framework', 'category': 'backend', 'aliases': ['asp.net', 'dotnet core']},

    # ======= モバイル・クロスプラットフォーム =======
    'Flutter': {'type': 'framework', 'category': 'mobile'},
    'React Native': {'type': 'framework', 'category': 'mobile', 'aliases': ['rn']},
    'Xamarin': {'type': 'framework', 'category': 'mobile'},
    'Unity': {'type': 'framework', 'category': 'game', 'aliases': ['unity3d']},
    'Unreal Engine': {'type': 'framework', 'category': 'game', 'aliases': ['ue4', 'ue5']},

    # ======= クラウド・インフラ =======
    'AWS': {'type': 'cloud', 'category': 'infrastructure', 'aliases': ['amazon web services']},
    'Azure': {'type': 'cloud', 'category': 'infrastructure', 'aliases': ['microsoft azure']},
    'GCP': {'type': 'cloud', 'category': 'infrastructure', 'aliases': ['google cloud', 'google cloud platform']},
    'Docker': {'type': 'devops', 'category': 'container'},
    'Kubernetes': {'type': 'devops', 'category': 'container', 'aliases': ['k8s', 'k3s', 'eks', 'aks', 'gke']},
    'Terraform': {'type': 'devops', 'category': 'iac', 'aliases': ['tf']},
    'Ansible': {'type': 'devops', 'category': 'configuration'},
    'Chef': {'type': 'devops', 'category': 'configuration'},
    'Puppet': {'type': 'devops', 'category': 'configuration'},
    'Jenkins': {'type': 'devops', 'category': 'ci_cd'},
    'GitHub Actions': {'type': 'devops', 'category': 'ci_cd'},
    'GitLab CI/CD': {'type': 'devops', 'category': 'ci_cd', 'aliases': ['gitlab ci']},
    'CircleCI': {'type': 'devops', 'category': 'ci_cd'},
    'Linux': {'type': 'os', 'category': 'infrastructure', 'aliases': ['ubuntu', 'centos', 'redhat', 'rhel', 'debian']},
    'Windows Server': {'type': 'os', 'category': 'infrastructure', 'aliases': ['win server']},
    'Nginx': {'type': 'tool', 'category': 'infrastructure', 'aliases': ['n-ginx']},
    'Apache': {'type': 'tool', 'category': 'infrastructure', 'aliases': ['httpd', 'apache http server']},
    'Tomcat': {'type': 'tool', 'category': 'infrastructure'},

    # ======= データベース =======
    'MySQL': {'type': 'database', 'category': 'relational', 'aliases': ['my sql']},
    'PostgreSQL': {'type': 'database', 'category': 'relational', 'aliases': ['postgres', 'postgre']},
    'Oracle': {'type': 'database', 'category': 'relational', 'aliases': ['oracle db']},
    'SQL Server': {'type': 'database', 'category': 'relational', 'aliases': ['mssql', 'ms sql', 'sqlserver']},
    'SQLite': {'type': 'database', 'category': 'relational'},
    'MongoDB': {'type': 'database', 'category': 'nosql', 'aliases': ['mongo']},
    'Redis': {'type': 'database', 'category': 'key-value'},
    'Memcached': {'type': 'database', 'category': 'key-value'},
    'DynamoDB': {'type': 'database', 'category': 'nosql'},
    'Cassandra': {'type': 'database', 'category': 'nosql'},
    'Elasticsearch': {'type': 'database', 'category': 'search', 'aliases': ['elastic search']},
    'Firebase': {'type': 'database', 'category': 'baas', 'aliases': ['firestore']},

    # ======= AI・データサイエンス =======
    'Machine Learning': {'type': 'skill', 'category': 'ai', 'aliases': ['ml', '機械学習']},
    'Deep Learning': {'type': 'skill', 'category': 'ai', 'aliases': ['dl', '深層学習']},
    'Data Science': {'type': 'skill', 'category': 'data', 'aliases': ['データサイエンス']},
    'PyTorch': {'type': 'library', 'category': 'ai'},
    'TensorFlow': {'type': 'library', 'category': 'ai', 'aliases': ['tf']},
    'Keras': {'type': 'library', 'category': 'ai'},
    'scikit-learn': {'type': 'library', 'category': 'ai', 'aliases': ['sklearn']},
    'Pandas': {'type': 'library', 'category': 'data'},
    'NumPy': {'type': 'library', 'category': 'data'},
    'LLM': {'type': 'skill', 'category': 'ai', 'aliases': ['large language model', 'chatgpt', 'openai']},

    # ======= デザイン・ツール =======
    'Figma': {'type': 'tool', 'category': 'design'},
    'Adobe XD': {'type': 'tool', 'category': 'design', 'aliases': ['xd']},
    'Photoshop': {'type': 'tool', 'category': 'design', 'aliases': ['ps']},
    'Illustrator': {'type': 'tool', 'category': 'design', 'aliases': ['ai']},
    'Git': {'type': 'tool', 'category': 'version-control'},
    'GitHub': {'type': 'tool', 'category': 'version-control'},
    'GitLab': {'type': 'tool', 'category': 'version-control'},
    'Subversion': {'type': 'tool', 'category': 'version-control', 'aliases': ['svn']},
    'Jira': {'type': 'tool', 'category': 'management'},
    'Confluence': {'type': 'tool', 'category': 'management'},
    'Slack': {'type': 'tool', 'category': 'communication'},

    # ======= 役割・工程 =======
    '要件定義': {'type': 'role', 'category': 'process', 'aliases': ['requirements definition', '要件定義書']},
    '基本設計': {'type': 'role', 'category': 'process', 'aliases': ['basic design', '基本設計書']},
    '詳細設計': {'type': 'role', 'category': 'process', 'aliases': ['detail design', '詳細設計書']},
    '実装': {'type': 'role', 'category': 'process', 'aliases': ['development', 'コーディング', 'プログラミング', '開発']},
    'テスト': {'type': 'role', 'category': 'process', 'aliases': ['testing', '単体テスト', '結合テスト', '総合テスト', 'システムテスト']},
    '運用保守': {'type': 'role', 'category': 'process', 'aliases': ['maintenance', 'operation', '保守', '運用', '運用・保守']},
    'プロジェクトマネージャー': {'type': 'role', 'category': 'management', 'aliases': ['pm', 'プロジェクトマネジメント', 'project manager']},
    'プロジェクトリーダー': {'type': 'role', 'category': 'management', 'aliases': ['pl', 'リーダー', 'project leader']},
    'スクラムマスター': {'type': 'role', 'category': 'management', 'aliases': ['scrum master', 'sm']},
    'アジャイル': {'type': 'methodology', 'category': 'process', 'aliases': ['agile', 'アジャイル開発']},
    'スクラム': {'type': 'methodology', 'category': 'process', 'aliases': ['scrum']},
    
    # ======= ソフトスキル =======
    'コミュニケーションスキル': {'type': 'soft', 'category': 'soft-skill', 'aliases': ['コミュニケーション', '対人スキル', '円滑なコミュニケーション', 'コミュニケーション能力', '折衝能力', '折衝', 'コミュ力']},
    'リーダーシップ': {'type': 'soft', 'category': 'soft-skill', 'aliases': ['牽引力', 'チームリード', 'マネジメントスキル', '後輩指導', 'チームビルディング', 'マネジメント']},
    '問題解決能力': {'type': 'soft', 'category': 'soft-skill', 'aliases': ['課題解決', '論理的思考', 'ロジカルシンキング', 'トラブルシューティング']},
    '主体性': {'type': 'soft', 'category': 'soft-skill', 'aliases': ['自走力', '自発的', 'キャッチアップ力', 'キャッチアップ']},
    '協調性': {'type': 'soft', 'category': 'soft-skill', 'aliases': ['チームワーク', 'チーム開発']},
    '英語力': {'type': 'soft', 'category': 'soft-skill', 'aliases': ['英語', 'english', 'toeic', 'ビジネス英語', '日常会話']}
}
